name: Build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Deps
        run: yarn install --frozen-lockfile # optional, --immutable
      - name: Build
        run: yarn build